// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3ZcpFUg2EtNIMHKLf3fRBSShoeWNm7P4',
    appId: '1:537021742973:web:a018ce8578f58575f65614',
    messagingSenderId: '537021742973',
    projectId: 'doctorappointment-77010',
    authDomain: 'doctorappointment-77010.firebaseapp.com',
    storageBucket: 'doctorappointment-77010.firebasestorage.app',
    measurementId: 'G-B5M5R1PVSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQP59pSfir5vCYrmmcOb5nU7zIgwC0SOo',
    appId: '1:537021742973:android:a39b75bfdf72b975f65614',
    messagingSenderId: '537021742973',
    projectId: 'doctorappointment-77010',
    storageBucket: 'doctorappointment-77010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYjyabQmchDEckqyjVIK516Dsh4MbTNFg',
    appId: '1:537021742973:ios:48eff8e2dc8269b2f65614',
    messagingSenderId: '537021742973',
    projectId: 'doctorappointment-77010',
    storageBucket: 'doctorappointment-77010.firebasestorage.app',
    iosBundleId: 'com.example.ecoms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYjyabQmchDEckqyjVIK516Dsh4MbTNFg',
    appId: '1:537021742973:ios:48eff8e2dc8269b2f65614',
    messagingSenderId: '537021742973',
    projectId: 'doctorappointment-77010',
    storageBucket: 'doctorappointment-77010.firebasestorage.app',
    iosBundleId: 'com.example.ecoms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3ZcpFUg2EtNIMHKLf3fRBSShoeWNm7P4',
    appId: '1:537021742973:web:07f58b6ff84199a4f65614',
    messagingSenderId: '537021742973',
    projectId: 'doctorappointment-77010',
    authDomain: 'doctorappointment-77010.firebaseapp.com',
    storageBucket: 'doctorappointment-77010.firebasestorage.app',
    measurementId: 'G-K6TBESV07B',
  );
}
